language: python
python:
  - "2.7"
install:
  - "pip install -r requirements.txt --use-wheel"
  - "pip install coveralls --use-wheel"
  - "pip install -e ."
services:
  - redis-server
script:
  - coverage run --source=numi_api `which trial` numi_api
after_success:
  - coveralls
